# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import statistic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInstancesChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('change_time', models.DateTimeField(editable=False)),
                ('change_type', models.CharField(max_length=50, validators=[statistic.models.trigger_validation])),
                ('pre_saved_data', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ModelInstancesChange',
                'verbose_name_plural': 'ModelInstancesChanges',
            },
        ),
    ]
