# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starosta',
            options={},
        ),
        migrations.RemoveField(
            model_name='starosta',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='starosta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starosta_of', to='students.Starosta'),
        ),
    ]
