# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20160523_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starosta',
            name='student',
        ),
        migrations.RemoveField(
            model_name='group',
            name='starosta',
        ),
        migrations.AddField(
            model_name='student',
            name='starosta',
            field=models.BooleanField(default=False, verbose_name='Назначить старостой'),
        ),
        migrations.DeleteModel(
            name='Starosta',
        ),
    ]
